CREATE SEQUENCE AMOUNT_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE ADD_AMOUNT_STATISTICS
(
    ID     NUMBER(10, 0) DEFAULT AMOUNT_SEQUENCE.nextval PRIMARY KEY,
    "START" TIMESTAMP WITH TIME ZONE NOT NULL,
    END TIMESTAMP WITH TIME ZONE NOT NULL,
    LAST_AMOUNTS NUMBER(10,0) DEFAULT 0,
    TOTAL_AMOUNTS NUMBER(10,0) DEFAULT 0
);

CREATE TABLE GET_AMOUNT_STATISTICS
(
    ID     NUMBER(10, 0) DEFAULT AMOUNT_SEQUENCE.nextval PRIMARY KEY,
    "START" TIMESTAMP WITH TIME ZONE NOT NULL,
    END TIMESTAMP WITH TIME ZONE NOT NULL,
    LAST_AMOUNTS NUMBER(10,0) DEFAULT 0,
    TOTAL_AMOUNTS NUMBER(10,0) DEFAULT 0
);